### ISSUE TITLE
Previous turn sometimes gets overlayed on top of the current turn, causing a mess

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/keldon-hanabi#10]

**Comment by Zamiell** [comment]
only happens sometimes.

it also seems to happen when using the modified ui.js/lobby.js on vanilla keldon

**Comment by aliblong** [comment]
I've only ever seen this bug during the very first clue I give, including while I was testing.

I can repro this most times on Chrome with vanilla Keldon server and client by hitting the "Lobby" button then rejoining the game, and immediately giving a clue. I can sometimes repro it under these same conditions, but instead of backing out the lobby and rejoining, I wait for some time before giving the clue (~45s). I have not yet reproduced it on Firefox.

**Comment by Zamiell** [comment]
So in conclusion:
- It's not a bug with the server code, since it happens on the original Keldon server.
- Its not a bug with the modified client code, since it happens on the original Keldon server with the extension turned off.

Needs further research; Instant said he had a hypothesis.

**Comment by Zamiell** [comment]
This didnt happen to me yesterday. Did @aliblong 's UI work somehow fix this bug ?

**Comment by Zamiell** [comment]
Has anyone gotten this recently?

**Comment by aliblong** [comment]
Nope, not for over a month.
