### ISSUE TITLE
Show partial faces in mixed variant during rewind 

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/keldon-hanabi#21]

**Comment by rogers-j** [comment]
The server explicitly reveals all cards in player hands. Is that all Keldon did? Or did it reveal all cards?

We might not have noticed because of Hyphen-ated's replay feature either way.

**Comment by Zamiell** [comment]
i just tested on vanilla keldon and its fucked. cards are hidden when the game ends and then you rewind backwards

**Comment by Zamiell** [comment]
TODO:
1) Re-enable the replay feature in the MHGA code
2) Disable the specific part where it shows color information with something along the lines of:
```
if (ui.variant === VARIANT.MIXED) {
    return;
}
```

**Comment by rogers-j** [comment]
Something like that: 15b9447a12c97610a9f7753f91336fb8ff9a93cd

At some point we should actually be able to undo 92e7bdb9012fdb7ccfb48deb16c88736b0838e17 when that feature and mixed suit are reconciled.

**Comment by Zamiell** [comment]
deleting my comments FeelsBadMan

**Comment by Zamiell** [comment]
The TODO for this issue:

1) Make cards show up properly in the replay for the mixed variant (4)
2) Make cards show up properly in the replay for the mixed+multi variant (5)

**Comment by rogers-j** [comment]
In addition to the image issue I described above, 63be5a2450fb6f52fc23099124b23b85786d723d was needed because the `learned_clues` collection makes no distinction between clued colors and card suits. (The code that updates it has special behavior for inferring rainbow cards from multiple suits.)

The most reasonable way I can see to address this is to treat each variant as an interface implementation. Expected behaviors include: 
- Generate all the appropriate images
- Maintain a collection of learned things about cards (i.e. when getting a new clue, incorporate the data)
- Find the image for a card given its full identity
- Find the image for a card based on the collection above
- Convert clue indexes to names for the clue and action logs
- Convert suit indexes to names for the action logs (unless this is moved entirely to the server)

When first building the UI, the client chooses the right implementation based on the variant. That choice could be represented by an object or just saving relevant functions. Then various functions, such as responding to an incoming message about a clued card, would call into the appropriate function. (The current behavior only does this for positive clues, but it could be easily done for negative clues as well.)

(Keldon wrote a separate tracking system that knows how to add multiple gradients to a card as it is clued, but we do not want to tamper with that feature for this purpose. It stripes a card if alternating color clues are given to it.)

**Comment by rogers-j** [comment]
This is overcome by other efforts to change how suit information is represented.
