### ISSUE TITLE
Add feature to see a card's face based on only holder's knowledge

### ISSUE THREAD

**Issue by Zamiell** [Zamiell/keldon-hanabi#78]
Follows from #59

**Comment by rogers-j** [comment]
After looking at a screenshot, aliblong brings up an excellent point: the user's cards are oriented inwards, while the cards of other players are oriented outwards. In the new view, the inverted orientation of the card is strongly indicated by the location of the rank pips. This is very confusing because the user is now viewing the hands of players such that they are 'discarding from the left' rather than the right.

Current investigation: invert the cards
